// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtJ2aReWfGlAUu30fwPZiIK6mbX82KKpA',
    appId: '1:449463685337:web:ec46fb1875b336f3712ec8',
    messagingSenderId: '449463685337',
    projectId: 'recetario-4bbb7',
    authDomain: 'recetario-4bbb7.firebaseapp.com',
    storageBucket: 'recetario-4bbb7.appspot.com',
    measurementId: 'G-HVSR199DCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQoJTDGWcSPJg_-l9X8cCXzhTqxiKC870',
    appId: '1:449463685337:android:c7473e20e56ac28d712ec8',
    messagingSenderId: '449463685337',
    projectId: 'recetario-4bbb7',
    storageBucket: 'recetario-4bbb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8dL4vj4rZiMZKdoEFhLctQCl_uSJ1PQc',
    appId: '1:449463685337:ios:3abd9447ffe96781712ec8',
    messagingSenderId: '449463685337',
    projectId: 'recetario-4bbb7',
    storageBucket: 'recetario-4bbb7.appspot.com',
    iosBundleId: 'com.example.appdani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8dL4vj4rZiMZKdoEFhLctQCl_uSJ1PQc',
    appId: '1:449463685337:ios:3abd9447ffe96781712ec8',
    messagingSenderId: '449463685337',
    projectId: 'recetario-4bbb7',
    storageBucket: 'recetario-4bbb7.appspot.com',
    iosBundleId: 'com.example.appdani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtJ2aReWfGlAUu30fwPZiIK6mbX82KKpA',
    appId: '1:449463685337:web:d06aff50df08a383712ec8',
    messagingSenderId: '449463685337',
    projectId: 'recetario-4bbb7',
    authDomain: 'recetario-4bbb7.firebaseapp.com',
    storageBucket: 'recetario-4bbb7.appspot.com',
    measurementId: 'G-FMVB7S1KYP',
  );
}
